### ISSUE TITLE
[INFORME O PROBLEMA] Tentei iniciar o software, mas ele não funciona.

### ISSUE THREAD

**Issue by marcosgf24872** [marcosgf2487/repositorioA#1]
*Problema:*
 O software não abre no Linux Mint 21 Vanessa.

*Data que você percebeu o problema:*
17//09/2023

*Sugestão de correção:*
Aprimorar o sistema de inicilização do software QIA+ .

**Comment by marcosgf2487** [comment]
Olá, Marcos! Muito obrigado por nos avisar sobre o problema. Em breve o software passará por atualização da versão atual, então o problema de inicialização estará corrigido. Agradecemos o seu contato! Estamos a disposição sempre que precisar!

**Comment by marcosgf2487** [comment]
Olá, Marcos! Gostaria de te avisar que o software já foi atualizado, e o sistema de inicialização já foi corrigido. Poderia nos informar se ele está abrindo no seu computador?Muito obrigado!

**Comment by marcosgf24872** [comment]
Oi! Está sim! Muito obrigado!

**Comment by marcosgf2487** [comment]
Nós é que agradecemos! Tudo de bom!

**Comment by marcosgf2487** [comment]
:)
